apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: orange-app
type: Opaque
stringData:
  MYSQL_DATABASE: orange_db
  MYSQL_USER: orange_app
  MYSQL_PASSWORD: orangepass
  MYSQL_ROOT_PASSWORD: rootpassword
